/*
  # Create entries for the 6 organizations shown in dashboard

  1. New Data
    - Insert 6 approved organization applications matching the dashboard organizations:
      - Education First (Education)
      - Clean Water Initiative (Health)
      - Forest Protection Fund (Environment)
      - Emergency Relief Network (Disaster Relief)
      - Community Development Alliance (Poverty Alleviation)
      - Human Rights Advocacy (Human Rights)

  2. Status
    - All organizations set to 'approved' status
    - Realistic founding dates and contact information
    - Comprehensive mission statements and program descriptions
*/

-- Insert the 6 organizations from the dashboard
INSERT INTO organization_applications (
  organization_name,
  country_registration,
  legal_status,
  registration_number,
  tax_identification,
  founding_date,
  address,
  website,
  primary_contact_name,
  primary_contact_email,
  organization_email,
  organization_phone,
  partner_affiliations,
  mission_statement,
  primary_category,
  geographic_focus,
  programs_services,
  beneficiaries,
  achievements,
  anti_terror_certification,
  terms_conditions,
  status,
  created_at
) VALUES 
(
  'Education First',
  'United States',
  '501(c)(3) Nonprofit Organization',
  'EF-2018-001234',
  '12-3456789',
  '2018',
  '1234 Learning Avenue, Boston, MA 02101, United States',
  'https://educationfirst.org',
  'Sarah Johnson',
  'sarah.johnson@educationfirst.org',
  'info@educationfirst.org',
  '+1 (617) 555-0123',
  'Member of Global Education Alliance, UNESCO Partner',
  'Education First is dedicated to providing quality education opportunities to underserved communities worldwide. We believe every child deserves access to learning resources and skilled teachers, regardless of their economic background.',
  'Education',
  'Sub-Saharan Africa, Southeast Asia, Latin America',
  'We operate teacher training programs, build schools in rural areas, provide educational materials and technology, and offer scholarship programs for promising students. Our mobile learning labs bring education directly to remote communities.',
  'We serve over 50,000 children annually across 12 countries, focusing on rural and marginalized communities where educational infrastructure is limited. Our programs have reached students in Kenya, Uganda, Cambodia, Guatemala, and Peru.',
  'Built 127 schools since 2018, trained over 2,500 teachers, provided scholarships to 1,200 students who have gone on to higher education. Winner of the Global Education Impact Award 2023.',
  true,
  true,
  'approved',
  '2024-01-15 10:30:00+00'
),
(
  'Clean Water Initiative',
  'Canada',
  'Registered Charity',
  'CWI-2019-567890',
  '123456789RC0001',
  '2019',
  '567 Water Street, Toronto, ON M5V 3A8, Canada',
  'https://cleanwaterinitiative.org',
  'Michael Chen',
  'michael.chen@cleanwaterinitiative.org',
  'contact@cleanwaterinitiative.org',
  '+1 (416) 555-0456',
  'Partner with Water.org, Member of Global Water Partnership',
  'Clean Water Initiative works to provide sustainable access to clean water and sanitation facilities in communities that need it most. We combine innovative technology with community-driven solutions to create lasting impact.',
  'Health',
  'East Africa, South Asia, Central America',
  'We install water purification systems, build wells and sanitation facilities, train local technicians for maintenance, and educate communities about water safety and hygiene practices. Our solar-powered water systems provide sustainable solutions.',
  'Our programs serve over 200,000 people across 8 countries, primarily in rural villages and urban slums where clean water access is limited. We focus on women and children who are most affected by water scarcity.',
  'Provided clean water access to 200,000+ people, built 450 wells, installed 89 solar water systems, trained 340 local technicians. Reduced waterborne illness by 78% in served communities.',
  true,
  true,
  'approved',
  '2024-02-20 14:15:00+00'
),
(
  'Forest Protection Fund',
  'Brazil',
  'Non-Governmental Organization (NGO)',
  'FPF-2017-789012',
  '12.345.678/0001-90',
  '2017',
  'Rua das Árvores, 123, São Paulo, SP 01234-567, Brazil',
  'https://forestprotectionfund.org',
  'Ana Silva',
  'ana.silva@forestprotectionfund.org',
  'info@forestprotectionfund.org',
  '+55 11 9876-5432',
  'Partner with WWF, Member of Amazon Conservation Association',
  'Forest Protection Fund is committed to preserving critical forest ecosystems and supporting indigenous communities who are the guardians of these lands. We work to combat deforestation and promote sustainable forest management.',
  'Environment',
  'Amazon Basin, Atlantic Forest, Cerrado Savanna',
  'We conduct forest monitoring using satellite technology, support indigenous land rights, fund reforestation projects, and promote sustainable livelihoods for forest communities. Our programs include carbon offset initiatives and biodiversity conservation.',
  'We work with 45 indigenous communities and have protected over 2.5 million hectares of forest. Our programs benefit approximately 15,000 indigenous people and countless wildlife species in critical ecosystems.',
  'Protected 2.5M hectares of forest, planted 500,000 trees, supported land rights for 45 indigenous communities, prevented deforestation of 180,000 hectares. UN Environment Programme Recognition 2022.',
  true,
  true,
  'approved',
  '2024-03-10 09:45:00+00'
),
(
  'Emergency Relief Network',
  'United Kingdom',
  'Registered Charity',
  'ERN-2020-345678',
  '1234567',
  '2020',
  '789 Relief Road, London SW1A 1AA, United Kingdom',
  'https://emergencyreliefnetwork.org',
  'James Wilson',
  'james.wilson@emergencyreliefnetwork.org',
  'emergency@reliefnetwork.org',
  '+44 20 7123 4567',
  'Member of Disasters Emergency Committee, Partner with UNICEF',
  'Emergency Relief Network provides rapid humanitarian assistance to communities affected by natural disasters and conflicts. We focus on immediate relief and long-term recovery to help communities rebuild stronger.',
  'Disaster Relief',
  'Global - with focus on Asia-Pacific, Caribbean, and Mediterranean regions',
  'We provide emergency shelter, clean water, medical supplies, and food assistance during crises. Our rapid response teams deploy within 72 hours of disasters. We also focus on disaster preparedness and community resilience building.',
  'We have responded to 23 major disasters since 2020, providing aid to over 500,000 people affected by earthquakes, hurricanes, floods, and conflicts. Our beneficiaries include displaced families, injured individuals, and vulnerable populations.',
  'Responded to 23 major disasters, aided 500,000+ people, deployed 156 emergency response missions, built 2,400 temporary shelters, provided medical care to 75,000 people. Humanitarian Excellence Award 2023.',
  true,
  true,
  'approved',
  '2024-04-05 16:20:00+00'
),
(
  'Community Development Alliance',
  'Kenya',
  'Non-Governmental Organization',
  'CDA-2016-901234',
  'P051234567A',
  '2016',
  'Uhuru Highway, Nairobi 00100, Kenya',
  'https://communitydevelopmentalliance.org',
  'Grace Wanjiku',
  'grace.wanjiku@communitydevelopmentalliance.org',
  'info@communitydevelopmentalliance.org',
  '+254 20 123 4567',
  'Member of Kenya Association of NGOs, Partner with UN-Habitat',
  'Community Development Alliance empowers communities to break the cycle of poverty through sustainable development programs. We focus on economic empowerment, skills training, and community-led initiatives that create lasting change.',
  'Poverty Alleviation',
  'East Africa - Kenya, Tanzania, Uganda',
  'We provide microfinance services, vocational training, agricultural support, and small business development programs. Our community savings groups and cooperative programs help families build financial resilience and economic independence.',
  'We serve over 75,000 people in rural and urban communities, with a focus on women, youth, and marginalized groups. Our programs reach smallholder farmers, aspiring entrepreneurs, and families living below the poverty line.',
  'Supported 15,000 small businesses, provided microloans to 8,500 women, trained 12,000 people in vocational skills, increased household income by average 65% in program areas. African Development Impact Award 2022.',
  true,
  true,
  'approved',
  '2024-05-12 11:30:00+00'
),
(
  'Human Rights Advocacy',
  'Netherlands',
  'Foundation (Stichting)',
  'HRA-2015-456789',
  'NL123456789B01',
  '2015',
  'Prinsengracht 456, 1017 KE Amsterdam, Netherlands',
  'https://humanrightsadvocacy.org',
  'Elena Rodriguez',
  'elena.rodriguez@humanrightsadvocacy.org',
  'advocacy@humanrights.org',
  '+31 20 123 4567',
  'Member of International Federation for Human Rights, Partner with Amnesty International',
  'Human Rights Advocacy works to protect and promote fundamental human rights worldwide. We provide legal support to victims of human rights violations, advocate for policy changes, and raise awareness about critical human rights issues.',
  'Human Rights',
  'Global - with focus on Latin America, Eastern Europe, and Southeast Asia',
  'We provide legal aid to human rights defenders, document violations, advocate for policy reform, and support civil society organizations. Our programs include protection for journalists, women''s rights advocacy, and support for marginalized communities.',
  'We have provided legal support to over 2,000 human rights defenders, documented 500+ cases of violations, and supported 150 civil society organizations. Our work benefits journalists, activists, indigenous peoples, and LGBTI+ individuals.',
  'Secured legal protection for 2,000+ human rights defenders, documented 500+ violation cases, influenced 12 policy changes, supported 150 civil society organizations. European Human Rights Award 2023.',
  true,
  true,
  'approved',
  '2024-06-18 13:45:00+00'
);